# Generated by Django 5.2.6 on 2025-09-20 14:19

from django.db import migrations, models


def add_updated_at_column(apps, schema_editor):
    """
    Add updated_at column if it doesn't exist
    """
    with schema_editor.connection.cursor() as cursor:
        # Check if updated_at column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='shop_product' AND column_name='updated_at'
        """)
        
        if not cursor.fetchone():
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE shop_product 
                ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            """)


def remove_updated_at_column(apps, schema_editor):
    """
    Remove updated_at column (reverse migration)
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE shop_product DROP COLUMN IF EXISTS updated_at")


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.RunPython(add_updated_at_column, remove_updated_at_column),
    ]
