# Generated by Django 5.2.6 on 2025-09-20 14:41

from django.db import migrations, models


def set_default_shop_types(apps, schema_editor):
    """
    Set default shop_type values for existing shops based on owner role
    """
    Shop = apps.get_model('shop', 'Shop')
    
    # Update existing shops to have appropriate shop_type
    for shop in Shop.objects.all():
        try:
            if shop.owner and hasattr(shop.owner, 'role'):
                if shop.owner.role == 'dropshipper':
                    shop.shop_type = 'dropshipper'
                else:
                    shop.shop_type = 'vendor'
            else:
                shop.shop_type = 'vendor'  # default fallback
        except Exception:
            shop.shop_type = 'vendor'  # safe fallback
        shop.save()


def reverse_shop_types(apps, schema_editor):
    """
    Reverse migration - set all shop_types to null
    """
    Shop = apps.get_model('shop', 'Shop')
    Shop.objects.all().update(shop_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20250920_1919'),
    ]

    operations = [
        # Since the column already exists in DB, we just need to update the existing records
        migrations.RunPython(set_default_shop_types, reverse_shop_types),
    ]
